import {
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';

const doseData = [
  { label: 'Q1 (0–1d)', low: 1.00, high: 1.00 },
  { label: 'Q2 (2–3d)', low: 1.08, high: 1.02 },
  { label: 'Q3 (4–5d)', low: 1.18, high: 1.04 },
  { label: 'Q4 (6–8d)', low: 1.31, high: 1.04 },
  { label: 'Q5 (9+d)',  low: 1.41, high: 1.05 },
];

export function ChenLabDeliverable(): React.JSX.Element {
  return (
    <div className="cld-wrap">
      {/* HEADER */}
      <div className="cld-doc-header">
        <div className="cld-doc-eye">Research Brief · Generated by Ambi · Apr 5, 2026</div>
        <div className="cld-doc-title">
          Chen Lab × Tobin Center<br />
          Heat Exposure &amp; Preterm Birth — CT Adaptation Pitch
        </div>
        <div className="cld-doc-meta">
          <div className="cld-meta-item"><strong>Sarah Chen</strong> (YSPH) × <strong>James Okafor</strong> (Tobin Center)</div>
          <div className="cld-meta-item"><strong>5</strong> insights surfaced</div>
          <div className="cld-meta-item"><strong>3</strong> action items before Thursday</div>
          <div className="cld-meta-item">June 2026 · CT legislative session window</div>
        </div>
      </div>

      {/* STATS */}
      <div className="cld-stat-row">
        <div className="cld-stat-card cld-c-green">
          <div className="cld-stat-label">Conservative Anchor</div>
          <div className="cld-stat-val">1.24</div>
          <div className="cld-stat-sub">RR lower bound · stable across specs</div>
        </div>
        <div className="cld-stat-card cld-c-red">
          <div className="cld-stat-label">In-Flux Estimate</div>
          <div className="cld-stat-val">1.41</div>
          <div className="cld-stat-sub">Q1/T3 central — AC confounder pending</div>
        </div>
        <div className="cld-stat-card cld-c-blue">
          <div className="cld-stat-label">Insights Surfaced</div>
          <div className="cld-stat-val">5</div>
          <div className="cld-stat-sub">2 reactive · 1 diagram · 1 caution · 1 proactive</div>
        </div>
        <div className="cld-stat-card cld-c-gold">
          <div className="cld-stat-label">Pitch Window</div>
          <div className="cld-stat-val">Jun</div>
          <div className="cld-stat-sub">CT legislative session closes</div>
        </div>
      </div>

      {/* DECISIONS + INSIGHTS */}
      <div className="cld-two-col">
        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-green" />Key Decisions &amp; Agreements</div>
          <div className="cld-dl">
            <div className="cld-di">
              <div className="cld-di-num">01</div>
              <div>
                <div className="cld-di-title">New Haven as anchor, Bridgeport as directional signal</div>
                <div className="cld-di-body">James agreed to frame pitch as New Haven-primary. Bridgeport data is thinner and estimates less stable — citing both equally risks credibility if Bridgeport estimates shift in peer review.</div>
                <div className="cld-tags">
                  <span className="cld-tag cld-t-done">Agreed</span>
                  <span className="cld-tag cld-t-info">Framing decision</span>
                </div>
              </div>
            </div>
            <div className="cld-di">
              <div className="cld-di-num">02</div>
              <div>
                <div className="cld-di-title">Use pilot justification framing — not city-wide cost-benefit</div>
                <div className="cld-di-body">Sarah flagged RR 1.41 (Q1/T3) as in flux due to AC access confounder. Conservative lower bound of 1.24 is stable and appropriate for the Tobin pitch. City-wide projection unsupported at this stage.</div>
                <div className="cld-tags">
                  <span className="cld-tag cld-t-done">Agreed</span>
                  <span className="cld-tag cld-t-risk">Data caveat</span>
                </div>
              </div>
            </div>
            <div className="cld-di">
              <div className="cld-di-num">03</div>
              <div>
                <div className="cld-di-title">Multi-agency approval pathway must be mapped before Thursday</div>
                <div className="cld-di-body">Policy sign-off (DEEP), capital funding (OPM), and data authorization (DPH) run in parallel — not sequence. DPH MOU with YSPH likely longest lead-time item (6–10 weeks).</div>
                <div className="cld-tags">
                  <span className="cld-tag cld-t-open">Action Required</span>
                  <span className="cld-tag cld-t-info">James + Sarah</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-blue" />Insights Surfaced by Ambi</div>
          <div className="cld-ic cld-ic-green">
            <div className="cld-ic-icon">✓</div>
            <div>
              <div className="cld-ic-lbl">Reactive · Effect sizes</div>
              <div className="cld-ic-txt"><strong>RR 1.24 is the stable anchor</strong> — holds across all model specs even if AC confounder reduces the Q1/T3 central estimate. Safe to use for pilot justification framing.</div>
            </div>
          </div>
          <div className="cld-ic cld-ic-green">
            <div className="cld-ic-icon">↗</div>
            <div>
              <div className="cld-ic-lbl">Reactive · Dose-response</div>
              <div className="cld-ic-txt"><strong>Income-stratified curves diverge sharply.</strong> Low-income tracts show steep monotonic increase with heat exposure. Higher-income tracts are essentially flat — consistent with AC access buffering effect. Corroborated by Chersich et al. (2025): heat waves increase preterm birth odds by 26% across 198 studies.</div>
            </div>
          </div>
          <div className="cld-ic cld-ic-warn">
            <div className="cld-ic-icon">⚠</div>
            <div>
              <div className="cld-ic-lbl">Caution · Bridgeport framing</div>
              <div className="cld-ic-txt"><strong>Don't lead with "New Haven and Bridgeport."</strong> Bridgeport tract-level sample sizes are thinner. If estimates shift post-peer-review, the adaptation office will have heard a two-city claim the published paper doesn't support.</div>
            </div>
          </div>
          <div className="cld-ic cld-ic-blue">
            <div className="cld-ic-icon">→</div>
            <div>
              <div className="cld-ic-lbl">Proactive · Not raised in meeting</div>
              <div className="cld-ic-txt"><strong>CT DEEP's urban heat mapping publishes this spring</strong> — overlapping directly with Tobin pitch prep. Could validate geographic targeting or create a competing narrative if tracts don't align. Neither Sarah nor James raised it.</div>
            </div>
          </div>
        </div>
      </div>

      {/* EFFECT SIZE TABLE + DOSE-RESPONSE CHART */}
      <div className="cld-two-col">
        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-green" />Effect Sizes — Stability by Stratum</div>
          <div className="cld-trig-box">
            <div className="cld-trig-lbl">Triggered by</div>
            <div className="cld-trig-txt">"The preprint isn't peer reviewed and we're still working through a confounder around AC access. I don't want to hand you a number that changes in revision." — Sarah Chen</div>
          </div>
          <table className="cld-etbl">
            <thead>
              <tr>
                <th>Stratum</th>
                <th>Income</th>
                <th>RR</th>
                <th>95% CI</th>
                <th>Stability</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="cld-td-dim">First trimester</td>
                <td>Q1</td>
                <td className="cld-td-ns">1.08</td>
                <td className="cld-td-ci">0.96–1.21</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr>
                <td className="cld-td-dim">First trimester</td>
                <td>Q2–Q3</td>
                <td className="cld-td-ns">1.05</td>
                <td className="cld-td-ci">0.98–1.13</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr>
                <td className="cld-td-dim">Second trimester</td>
                <td>Q1</td>
                <td className="cld-td-sig">1.19</td>
                <td className="cld-td-ci">1.07–1.32</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr>
                <td className="cld-td-dim">Second trimester</td>
                <td>Q2–Q3</td>
                <td className="cld-td-sig">1.11</td>
                <td className="cld-td-ci">1.02–1.20</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr className="cld-flux-row">
                <td className="cld-td-dim">⚠ Third trimester</td>
                <td>Q1</td>
                <td className="cld-td-warn">1.41</td>
                <td className="cld-td-ci">1.24–1.60</td>
                <td><span className="cld-badge cld-b-flux">In flux</span></td>
              </tr>
              <tr>
                <td className="cld-td-dim">Third trimester</td>
                <td>Q2–Q3</td>
                <td className="cld-td-sig">1.18</td>
                <td className="cld-td-ci">1.09–1.28</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr>
                <td className="cld-td-dim">Third trimester</td>
                <td>Q4</td>
                <td className="cld-td-ns">1.03</td>
                <td className="cld-td-ci">0.95–1.12</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
            </tbody>
          </table>
          <div className="cld-anchor-box" style={{ marginTop: '12px' }}>
            <div className="cld-anchor-num">1.24</div>
            <div>
              <div className="cld-anchor-lbl">✓ Conservative anchor for Thursday pitch</div>
              <div className="cld-anchor-txt">CI lower bound — holds even if AC confounder shifts the central estimate. Appropriate for pilot justification, not city-wide projection.</div>
            </div>
          </div>
          <div className="cld-src-row">
            <div className="cld-src-tag">ambi_data_effect_sizes.json</div>
            <div className="cld-src-tag">Chen Lab preprint v2 · not peer reviewed</div>
          </div>
        </div>

        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-blue" />Dose-Response by Income Stratum</div>
          <div className="cld-trig-box">
            <div className="cld-trig-lbl">Triggered by</div>
            <div className="cld-trig-txt">"Around 1.4 relative risk in that stratum. Even if AC shaves that down, the directionality is stable." — Sarah Chen</div>
          </div>
          <div className="cld-chart-wrap">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={doseData} margin={{ top: 4, right: 8, left: 0, bottom: 4 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e4e2dc" />
                <XAxis
                  dataKey="label"
                  tick={{ fontFamily: 'DM Sans', fontSize: 10, fill: '#6b6a66' }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  domain={[0.95, 1.55]}
                  tickFormatter={(v: number) => 'RR ' + v.toFixed(2)}
                  tick={{ fontFamily: 'DM Mono', fontSize: 9, fill: '#a8a7a2' }}
                  axisLine={false}
                  tickLine={false}
                  width={56}
                />
                <Tooltip
                  formatter={(value, name) => ['RR ' + (Number(value)).toFixed(2), name]}
                  contentStyle={{ fontFamily: 'DM Sans', fontSize: 11, border: '1px solid #e4e2dc', borderRadius: 8 }}
                />
                <Legend
                  wrapperStyle={{ fontFamily: 'DM Sans', fontSize: 11, color: '#6b6a66', paddingTop: 8 }}
                  iconSize={12}
                />
                <Line
                  type="monotone"
                  dataKey="low"
                  name="Low-income (Q1)"
                  stroke="#b8291c"
                  strokeWidth={2}
                  dot={{ r: 4, fill: '#b8291c' }}
                  activeDot={{ r: 5 }}
                />
                <Line
                  type="monotone"
                  dataKey="high"
                  name="Higher-income (Q2–Q4)"
                  stroke="#185FA5"
                  strokeWidth={2}
                  strokeDasharray="4 3"
                  dot={{ r: 4, fill: '#185FA5' }}
                  activeDot={{ r: 5 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
          <div className="cld-ic cld-ic-green" style={{ marginTop: '8px' }}>
            <div className="cld-ic-icon">↑</div>
            <div>
              <div className="cld-ic-lbl">Diverging curves — policy implication</div>
              <div className="cld-ic-txt">Low-income tracts: steep monotonic increase. Higher-income: flat — consistent with AC buffering. <strong>Directionality is stable even if Q5 central estimate shifts.</strong> Supports geographically targeted pilot in low-income, high-heat tracts. Corroborated: Chersich et al. (2025), OR = 1.26 across 198 studies.</div>
            </div>
          </div>
          <div className="cld-src-row">
            <div className="cld-src-tag">ambi_data_rr_graph.json</div>
            <div className="cld-src-tag">Chersich et al. (2025) · Nature Medicine</div>
          </div>
        </div>
      </div>

      {/* STAKEHOLDER FLOW + DEEP PROACTIVE */}
      <div className="cld-two-col">
        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-gold" />CT Stakeholder Sign-Off Pathway</div>
          <div className="cld-trig-box">
            <div className="cld-trig-lbl">Triggered by</div>
            <div className="cld-trig-txt">"The adaptation office reports to DEEP, funding runs through OPM — and we'd need DPH sign-off to use the maternal outcomes data publicly." — James Okafor</div>
          </div>
          <div className="cld-flow">
            <div className="cld-flow-node cld-fn-blue">
              <span className="cld-fn-label">Entry point</span>
              Tobin Center pitch → CT Climate Adaptation Office (June session window)
            </div>
            <div className="cld-flow-arr">▼ concept approval</div>
            <div className="cld-flow-node cld-fn-blue">
              <span className="cld-fn-label">Policy track · DEEP</span>
              CT Dept. of Energy &amp; Environmental Protection — program sign-off
            </div>
            <div className="cld-flow-arr">▼ two parallel tracks required</div>
            <div className="cld-flow-parallel">
              <div className="cld-flow-node cld-fn-gold" style={{ marginBottom: 0 }}>
                <span className="cld-fn-label">Funding · OPM</span>
                Cool corridor capital — Governor's Office climate budget authorization
              </div>
              <div className="cld-flow-node cld-fn-warn" style={{ marginBottom: 0 }}>
                <span className="cld-fn-label">Data auth · DPH ⚠</span>
                CT DPH maternal outcomes public use auth → IRB + YSPH data MOU<br />
                <strong style={{ fontSize: '10px' }}>Est. 6–10 weeks — longest lead-time item</strong>
              </div>
            </div>
            <div className="cld-flow-arr">▼ both tracks cleared</div>
            <div className="cld-flow-node cld-fn-green">
              <span className="cld-fn-label">Outcome</span>
              New Haven pilot launch — cool corridor program, geographically targeted
            </div>
          </div>
          <div className="cld-src-row">
            <div className="cld-src-tag">CT agency structure · DEEP / OPM / DPH</div>
            <div className="cld-src-tag">Generated from conversation context</div>
          </div>
        </div>

        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-blue" />Proactive · DEEP Heat Mapping Timing Risk</div>
          <div className="cld-ic cld-ic-blue" style={{ marginBottom: '12px' }}>
            <div className="cld-ic-icon">→</div>
            <div>
              <div className="cld-ic-lbl">Not raised by either party · Ambi noticed</div>
              <div className="cld-ic-txt"><strong>CT DEEP's urban heat vulnerability index publishes spring 2026</strong> — directly overlapping with Tobin pitch prep. Could validate geographic targeting or create a competing narrative.</div>
            </div>
          </div>
          <div className="cld-tl">
            <div className="cld-tl-item">
              <div className="cld-tl-dot cld-td-past" />
              <div className="cld-tl-date">2023</div>
              <div className="cld-tl-txt">CT DEEP launches census tract-level heat vulnerability index project — New Haven, Bridgeport, Hartford, Waterbury</div>
            </div>
            <div className="cld-tl-item">
              <div className="cld-tl-dot cld-td-past" />
              <div className="cld-tl-date">Mar 2026</div>
              <div className="cld-tl-txt">Chen Lab preprint submitted · Tobin Center engagement begins</div>
            </div>
            <div className="cld-tl-item">
              <div className="cld-tl-dot cld-td-now" />
              <div className="cld-tl-date">Spring 2026</div>
              <div className="cld-tl-txt"><strong>DEEP expected to publish updated indices</strong> — overlaps directly with pitch prep window</div>
            </div>
            <div className="cld-tl-item">
              <div className="cld-tl-dot cld-td-risk" />
              <div className="cld-tl-date">June 2026</div>
              <div className="cld-tl-txt">Tobin / adaptation office pitch · CT legislative session closes</div>
            </div>
          </div>
          <div className="cld-sc-grid">
            <div className="cld-sc-card cld-sc-val">
              <div className="cld-sc-lbl">✓ Best case</div>
              <div className="cld-sc-txt">DEEP indices align with Chen Lab tracts — cite as independent state-agency validation. Major credibility boost.</div>
            </div>
            <div className="cld-sc-card cld-sc-risk">
              <div className="cld-sc-lbl">⚠ Risk case</div>
              <div className="cld-sc-txt">Indices conflict — pitch must address discrepancy proactively. Don't let the adaptation office find it first.</div>
            </div>
          </div>
          <div className="cld-src-row">
            <div className="cld-src-tag">CT DEEP urban heat island project</div>
            <div className="cld-src-tag">CT climate adaptation legislative calendar</div>
          </div>
        </div>
      </div>

      {/* ACTIONS + ROADMAP */}
      <div className="cld-two-col">
        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-gold" />Action Items Before Thursday</div>
          <table className="cld-atbl">
            <thead>
              <tr>
                <th>Action</th>
                <th>Owner</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Check DEEP project page for updated publication date — review tract overlap with Chen Lab data if indices drop before Thursday</td>
                <td><span className="cld-own">James</span></td>
                <td><span className="cld-pri-hi">High</span></td>
              </tr>
              <tr>
                <td>Draft one slide referencing DEEP as validation — or proactively acknowledging geographic discrepancy if tracts conflict. Consider contacting DEEP's climate office for pre-publication preview.</td>
                <td><span className="cld-own">James + Sarah</span></td>
                <td><span className="cld-pri-hi">High</span></td>
              </tr>
              <tr>
                <td>Map DPH data-sharing MOU timeline — 6–10 week lead time means process must start before June pitch to have data auth in hand at pilot launch</td>
                <td><span className="cld-own">Sarah (YSPH)</span></td>
                <td><span className="cld-pri-hi">High</span></td>
              </tr>
              <tr>
                <td>Reframe all pitch language as "New Haven anchor, Bridgeport directional" — remove "New Haven and Bridgeport" equivalence framing from deck</td>
                <td><span className="cld-own">James</span></td>
                <td><span className="cld-pri-md">Medium</span></td>
              </tr>
              <tr>
                <td>Build economic model using RR 1.24 as conservative anchor — NICHD $50K/preterm birth cost basis. Do not use RR 1.41 as a point estimate without uncertainty flagging.</td>
                <td><span className="cld-own">James</span></td>
                <td><span className="cld-pri-md">Medium</span></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-blue" />Pitch Preparation Roadmap</div>
          <div className="cld-rm">
            <div className="cld-rm-item">
              <div className="cld-rm-date">Before Thu</div>
              <div>
                <div className="cld-rm-title">Check DEEP publication window</div>
                <div className="cld-rm-body">Verify if indices drop before Thursday meeting. If yes — review tract overlap immediately and update deck framing.</div>
                <span className="cld-rs cld-rs-now">● Urgent</span>
              </div>
            </div>
            <div className="cld-rm-item">
              <div className="cld-rm-date">Before Thu</div>
              <div>
                <div className="cld-rm-title">Initiate DPH data-sharing MOU process</div>
                <div className="cld-rm-body">6–10 week estimated lead time. Must begin now to have data authorization cleared before pilot launch post-June pitch.</div>
                <span className="cld-rs cld-rs-now">● Urgent</span>
              </div>
            </div>
            <div className="cld-rm-item">
              <div className="cld-rm-date">Thu meeting</div>
              <div>
                <div className="cld-rm-title">Finalize economic model with RR 1.24 anchor</div>
                <div className="cld-rm-body">NICHD $50K/preterm birth × prevented births in low-income New Haven tracts. Pilot justification framing — not city-wide projection.</div>
                <span className="cld-rs cld-rs-next">→ Next</span>
              </div>
            </div>
            <div className="cld-rm-item">
              <div className="cld-rm-date">Pre-June</div>
              <div>
                <div className="cld-rm-title">Deck finalized · DEEP slide included</div>
                <div className="cld-rm-body">Either reference DEEP as validation or preemptively address any discrepancy. Lead with "New Haven anchor" framing throughout.</div>
                <span className="cld-rs cld-rs-next">→ Planned</span>
              </div>
            </div>
            <div className="cld-rm-item">
              <div className="cld-rm-date">June 2026</div>
              <div>
                <div className="cld-rm-title">Tobin / adaptation office pitch · CT legislative session</div>
                <div className="cld-rm-body">Window closes with the legislative session. OPM and DPH tracks must be in motion by this date for pilot to proceed on timeline.</div>
                <span className="cld-rs cld-rs-plan">Planned</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* SOURCE FOOTER */}
      <div className="cld-src-row">
        <div className="cld-src-tag">ambi_data_effect_sizes.json</div>
        <div className="cld-src-tag">ambi_data_rr_graph.json</div>
        <div className="cld-src-tag">Chersich et al. (2025) · Nature Medicine Vol. 31</div>
        <div className="cld-src-tag">CT DEEP urban heat island mapping project</div>
        <div className="cld-src-tag">CT climate adaptation legislative calendar · spring 2026</div>
        <div className="cld-src-tag">Chen Lab preprint v2 · not peer reviewed · uploaded 2026-03-18</div>
      </div>
    </div>
  );
}
