import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';

const uptakeData = [
  { zip: 'Brighton Park\n60632', pct: 29, color: '#a8a7a2', status: 'Not selected' },
  { zip: 'Little Village\n60623', pct: 38, color: '#A529F3', status: 'Pilot ✓' },
  { zip: 'Garfield Park\n60624', pct: 41, color: '#A529F3', status: 'Pilot ✓' },
  { zip: 'West Englewood\n60636', pct: 44, color: '#A529F3', status: 'Pilot ✓' },
  { zip: 'Roseland ⚠\n60628', pct: 52, color: '#e0a060', status: 'In flux' },
];

const CustomTick = (props: { x?: number; y?: number; payload?: { value: string } }) => {
  const { x = 0, y = 0, payload } = props;
  if (!payload) return null;
  const lines = payload.value.split('\n');
  return (
    <g transform={`translate(${x},${y})`}>
      <text x={0} y={0} dy={4} textAnchor="end" fill="#6b6a66" fontSize={9} fontFamily="DM Sans">
        {lines[0]}
      </text>
      <text x={0} y={0} dy={14} textAnchor="end" fill="#a8a7a2" fontSize={8} fontFamily="DM Mono">
        {lines[1]}
      </text>
    </g>
  );
};

export function PatelLabDeliverable(): React.JSX.Element {
  return (
    <div className="cld-wrap">
      {/* HEADER */}
      <div className="cld-doc-header">
        <div className="cld-doc-eye">Research Brief · Generated by Ambi · Apr 17, 2026</div>
        <div className="cld-doc-title">
          Patel Lab × Children's Hospital Foundation<br />
          Mobile Vaccine Clinic Rollout — Chicago Pilot
        </div>
        <div className="cld-doc-meta">
          <div className="cld-meta-item"><strong>James Okafor</strong> (Deloitte Health Equity) × <strong>Priya Patel</strong> (Patel Lab, CPHD)</div>
          <div className="cld-meta-item"><strong>3</strong> Ambi insights surfaced</div>
          <div className="cld-meta-item"><strong>5</strong> next steps before board meeting</div>
          <div className="cld-meta-item">Apr 17, 2026 · 2:12–2:44 PM</div>
        </div>
      </div>

      {/* STATS */}
      <div className="cld-stat-row">
        <div className="cld-stat-card cld-c-green">
          <div className="cld-stat-label">Pilot Zip Codes</div>
          <div className="cld-stat-val">3</div>
          <div className="cld-stat-sub">Little Village · Garfield Park · West Englewood</div>
        </div>
        <div className="cld-stat-card cld-c-blue">
          <div className="cld-stat-label">Conservative Anchor</div>
          <div className="cld-stat-val">37%</div>
          <div className="cld-stat-sub">CI lower bound · Garfield Park · board-safe</div>
        </div>
        <div className="cld-stat-card cld-c-red">
          <div className="cld-stat-label">Excluded · Phase 2</div>
          <div className="cld-stat-val">Roseland</div>
          <div className="cld-stat-sub">Clinic closure mid-collection · 52% unreliable</div>
        </div>
        <div className="cld-stat-card cld-c-gold">
          <div className="cld-stat-label">Insights Surfaced</div>
          <div className="cld-stat-val">3</div>
          <div className="cld-stat-sub">1 reactive · 1 diagram · 1 caution</div>
        </div>
      </div>

      {/* DECISIONS + INSIGHTS */}
      <div className="cld-two-col">
        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-green" />Decisions Made in This Meeting</div>
          <div className="cld-dl">
            <div className="cld-di">
              <div className="cld-di-num">✓</div>
              <div>
                <div className="cld-di-title">Pilot shortlist confirmed</div>
                <div className="cld-di-body">Little Village (60623), Garfield Park (60624), and West Englewood (60636) are the three zip codes for the fall pilot. All three have stable uptake estimates, consistent Q1 income profiles, and no outstanding data quality flags.</div>
                <div className="cld-tags">
                  <span className="cld-tag cld-t-done">Agreed</span>
                  <span className="cld-tag cld-t-info">Phase 1</span>
                </div>
              </div>
            </div>
            <div className="cld-di">
              <div className="cld-di-num">✗</div>
              <div>
                <div className="cld-di-title">Roseland excluded — deferred to Phase 2</div>
                <div className="cld-di-body">Roseland (60628) will not appear in the board pitch. The 52% figure reflects a clinic closure mid-collection, not stable underlying demand. Priya to flag in dataset footnotes. James to prepare one-line board response if Roseland comes up.</div>
                <div className="cld-tags">
                  <span className="cld-tag cld-t-risk">Excluded</span>
                  <span className="cld-tag cld-t-open">Phase 2</span>
                </div>
              </div>
            </div>
            <div className="cld-di">
              <div className="cld-di-num">→</div>
              <div>
                <div className="cld-di-title">Conservative anchor set for board pitch</div>
                <div className="cld-di-body">The 37% CI lower bound for Garfield Park is the headline figure James will use in the pitch deck. Holds even if minor data cleaning shifts the central estimate. Consistent with published benchmarks for mobile clinic impact thresholds.</div>
                <div className="cld-tags">
                  <span className="cld-tag cld-t-done">Agreed</span>
                  <span className="cld-tag cld-t-info">Framing decision</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-blue" />Insights Surfaced by Ambi</div>
          <div className="cld-trig-box" style={{ marginBottom: '10px' }}>
            <div className="cld-trig-lbl">Reactive · 01</div>
            <div className="cld-trig-txt">Zip code uptake table with stability flags fired when James asked which figures were reliable enough to anchor on. Pulled from ambi_data_vaccine_uptake.json.</div>
          </div>
          <div className="cld-trig-box" style={{ marginBottom: '10px' }}>
            <div className="cld-trig-lbl">Diagram Suggested · 01</div>
            <div className="cld-trig-txt">Site selection approval pathway mapped as a branching flowchart when Priya named three non-sequential sign-offs. Hospital network and CDPH tracks run in parallel.</div>
          </div>
          <div className="cld-trig-box">
            <div className="cld-trig-lbl">Caution · 01</div>
            <div className="cld-trig-txt">Roseland data quality flag fired when Priya described the clinic closure. Identified supply-vs-demand distinction and surfaced prepared board response language.</div>
          </div>
        </div>
      </div>

      {/* ZIP CODE DATA TABLE + BAR CHART */}
      <div className="cld-two-col">
        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-green" />Data Reviewed · Vaccine Uptake by Zip Code</div>
          <div className="cld-trig-box">
            <div className="cld-trig-lbl">Triggered by</div>
            <div className="cld-trig-txt">"I have the data. But not all of the uptake numbers are equally reliable — some I'm confident in, one I'm not." — Priya Patel</div>
          </div>
          <table className="cld-etbl">
            <thead>
              <tr>
                <th>Zip / Neighborhood</th>
                <th>Income</th>
                <th>% Unvax</th>
                <th>95% CI</th>
                <th>Stability</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="cld-td-dim">60623 · Little Village</td>
                <td className="cld-td-dim">Q1</td>
                <td className="cld-td-sig">38%</td>
                <td className="cld-td-ci">35–41%</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr>
                <td className="cld-td-dim">60624 · Garfield Park</td>
                <td className="cld-td-dim">Q1</td>
                <td className="cld-td-sig">41%</td>
                <td className="cld-td-ci">37–45%</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr>
                <td className="cld-td-dim">60636 · West Englewood</td>
                <td className="cld-td-dim">Q1</td>
                <td className="cld-td-sig">44%</td>
                <td className="cld-td-ci">40–48%</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr>
                <td className="cld-td-dim">60632 · Brighton Park</td>
                <td className="cld-td-dim">Q2</td>
                <td className="cld-td-ns">29%</td>
                <td className="cld-td-ci">26–32%</td>
                <td><span className="cld-badge cld-b-stable">Stable</span></td>
              </tr>
              <tr className="cld-flux-row">
                <td className="cld-td-dim">⚠ 60628 · Roseland</td>
                <td className="cld-td-dim">Q1</td>
                <td className="cld-td-warn">52%</td>
                <td className="cld-td-ci">46–58% · clinic closure flag</td>
                <td><span className="cld-badge cld-b-flux">In flux</span></td>
              </tr>
            </tbody>
          </table>
          <div className="cld-anchor-box" style={{ marginTop: '12px' }}>
            <div className="cld-anchor-num">37%</div>
            <div>
              <div className="cld-anchor-lbl">✓ Conservative anchor for the board pitch</div>
              <div className="cld-anchor-txt">CI lower bound for Garfield Park — holds even if minor data cleaning shifts the central estimate. Stable across 2023–2025 collection window. Consistent with Rennert et al. (2024): mobile clinics had greatest impact in communities with 35%+ unvaccinated rates.</div>
            </div>
          </div>
          <div className="cld-src-row">
            <div className="cld-src-tag">ambi_data_vaccine_uptake.json</div>
            <div className="cld-src-tag">Patel Lab CPHD dataset v3 · not peer reviewed · 2026-03-20</div>
          </div>
        </div>

        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-blue" />Unvaccinated Rate by Zip Code</div>
          <div className="cld-chart-wrap" style={{ height: '200px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={uptakeData}
                layout="vertical"
                margin={{ top: 4, right: 32, left: 88, bottom: 4 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="#e4e2dc" horizontal={false} />
                <XAxis
                  type="number"
                  domain={[0, 60]}
                  tickFormatter={(v: number) => `${v}%`}
                  tick={{ fontFamily: 'DM Mono', fontSize: 9, fill: '#a8a7a2' }}
                  axisLine={false}
                  tickLine={false}
                />
                <YAxis
                  type="category"
                  dataKey="zip"
                  tick={<CustomTick />}
                  axisLine={false}
                  tickLine={false}
                  width={88}
                />
                <Tooltip
                  formatter={(value) => [`${value}%`, 'Unvaccinated']}
                  contentStyle={{ fontFamily: 'DM Sans', fontSize: 11, border: '1px solid #e4e2dc', borderRadius: 8 }}
                />
                <Bar dataKey="pct" radius={[0, 3, 3, 0]} barSize={14}>
                  {uptakeData.map((entry, i) => (
                    <Cell key={i} fill={entry.color} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginTop: '8px' }}>
            <span className="cld-badge cld-b-stable" style={{ fontSize: '10px' }}>■ Pilot ✓</span>
            <span style={{ fontSize: '10px', color: '#a8a7a2', fontFamily: 'DM Sans', padding: '2px 6px' }}>■ Not selected</span>
            <span className="cld-badge cld-b-flux" style={{ fontSize: '10px' }}>■ In flux — excluded</span>
          </div>
          {/* Roseland caution */}
          <div className="cld-ic cld-ic-warn" style={{ marginTop: '12px' }}>
            <div className="cld-ic-icon">⚠</div>
            <div>
              <div className="cld-ic-lbl">Data flag · Roseland 60628 — do not cite in board materials</div>
              <div className="cld-ic-txt">The 52% figure reflects a supply disruption, not underlying demand. The Roseland Primary Care Clinic closed October 2024 mid-collection. If Roseland comes up in the board meeting: <strong>"Roseland is a strong Phase 2 candidate — we excluded it because a clinic closure during data collection makes the current figure unreliable as a demand signal."</strong></div>
            </div>
          </div>
          <div className="cld-src-row">
            <div className="cld-src-tag">ambi_data_vaccine_uptake.json</div>
            <div className="cld-src-tag">Rennert L et al. (2024) · Public Health Practice</div>
          </div>
        </div>
      </div>

      {/* APPROVAL PATHWAY + NEXT STEPS */}
      <div className="cld-two-col">
        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-gold" />Approval Pathway · From Shortlist to Clinic Date</div>
          <div className="cld-trig-box">
            <div className="cld-trig-lbl">Triggered by</div>
            <div className="cld-trig-txt">"It's not one approval — it's three, and they don't run in order." — Priya Patel</div>
          </div>
          <div className="cld-flow">
            <div className="cld-flow-node cld-fn-blue">
              <span className="cld-fn-label">Step 1 · Data</span>
              Zip code risk scoring confirmed — unvax rate + income quartile + population weight
            </div>
            <div className="cld-flow-arr">▼ two parallel tracks required</div>
            <div className="cld-flow-parallel">
              <div className="cld-flow-node cld-fn-gold" style={{ marginBottom: 0 }}>
                <span className="cld-fn-label">Track A · Hospital network</span>
                Clinical staff + van availability · Children's Hospital Foundation sign-off
              </div>
              <div className="cld-flow-node cld-fn-gold" style={{ marginBottom: 0 }}>
                <span className="cld-fn-label">Track B · City health dept (CDPH)</span>
                Protect Chicago+ alignment · zip eligibility check · outreach coordination
              </div>
            </div>
            <div className="cld-flow-arr">▼ both tracks cleared</div>
            <div className="cld-flow-node cld-fn-blue">
              <span className="cld-fn-label">Step 3 · Host site</span>
              School, church, or community center confirms date — 3-week lead time required
            </div>
            <div className="cld-flow-arr">▼</div>
            <div className="cld-flow-node cld-fn-green">
              <span className="cld-fn-label">Step 4 · Confirmed</span>
              Mobile clinic date locked · community outreach triggered · logistics confirmed
            </div>
          </div>
          <div className="cld-src-row">
            <div className="cld-src-tag">Woodson et al. (2024) · J Public Health Mgmt Practice</div>
            <div className="cld-src-tag">CDPH Protect Chicago+ · Generated from conversation context</div>
          </div>
        </div>

        <div className="cld-card">
          <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-gold" />Next Steps · Owners and Deadlines</div>
          <table className="cld-atbl">
            <thead>
              <tr>
                <th>Action</th>
                <th>Owner</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Update board pitch deck — swap Roseland for Phase 2 language, lead with 37% Garfield Park lower bound as headline figure</td>
                <td><span className="cld-own">James</span></td>
                <td><span className="cld-pri-hi">Urgent</span></td>
              </tr>
              <tr>
                <td>Initiate parallel outreach to Children's Hospital Foundation clinical ops and CDPH Protect Chicago+ coordinator — both tracks must start simultaneously</td>
                <td><span className="cld-own">James</span></td>
                <td><span className="cld-pri-hi">This week</span></td>
              </tr>
              <tr>
                <td>Add dataset footnote flagging Roseland clinic closure and add stability annotations to shared data file for foundation's records team</td>
                <td><span className="cld-own">Priya</span></td>
                <td><span className="cld-pri-md">End of week</span></td>
              </tr>
              <tr>
                <td>Identify host site contacts in Little Village, Garfield Park, and West Englewood — schools, churches, community centers for Step 3 sign-off</td>
                <td><span className="cld-own">James + Priya</span></td>
                <td><span className="cld-pri-md">2 weeks</span></td>
              </tr>
              <tr>
                <td>Monitor Roseland access situation — flag to James when data collection resumes cleanly so Roseland can be re-evaluated for Phase 2 targeting</td>
                <td><span className="cld-own">Priya</span></td>
                <td><span className="cld-pri-lo">Ongoing</span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* AMBI INSIGHT LOG */}
      <div className="cld-card" style={{ marginTop: '0' }}>
        <div className="cld-sec-label"><span className="cld-sec-dot cld-sd-blue" />Ambi Insight Log · 3 insights surfaced during this meeting</div>
        <div className="cld-dl">
          <div className="cld-di">
            <div className="cld-di-num">01</div>
            <div>
              <div className="cld-di-title">Reactive · Zip code uptake table with stability flags</div>
              <div className="cld-di-body">Surfaced when James asked which figures were reliable enough to anchor on. Pulled from ambi_data_vaccine_uptake.json — showed all five zip codes with CI ranges and in-flux flags. Fired after: <em>"Which ones are solid? Walk me through the ones you'd actually anchor on."</em></div>
              <div className="cld-tags"><span className="cld-tag cld-t-info">~2:18 PM</span><span className="cld-tag cld-t-blue">From uploaded dataset</span></div>
            </div>
          </div>
          <div className="cld-di">
            <div className="cld-di-num">02</div>
            <div>
              <div className="cld-di-title">Diagram Suggested · Site selection approval pathway</div>
              <div className="cld-di-body">Mapped as a branching flowchart when Priya named three non-sequential decision-makers. Illustrated that hospital network and CDPH tracks run in parallel before host site sign-off. Typical timeline: 4–6 weeks. Fired after: <em>"…not one approval — it's three, and they don't run in order."</em></div>
              <div className="cld-tags"><span className="cld-tag cld-t-info">~2:26 PM</span><span className="cld-tag cld-t-blue">Generated from context</span></div>
            </div>
          </div>
          <div className="cld-di">
            <div className="cld-di-num">03</div>
            <div>
              <div className="cld-di-title">Caution · Roseland data quality flag</div>
              <div className="cld-di-body">Fired when Priya described the clinic closure. Identified clinic_closed_flag in dataset, surfaced supply-vs-demand distinction, and provided prepared board response language. Fired after: <em>"A community clinic closed in Roseland right in the middle of data collection."</em></div>
              <div className="cld-tags"><span className="cld-tag cld-t-info">~2:33 PM</span><span className="cld-tag cld-t-risk">Data quality risk</span></div>
            </div>
          </div>
        </div>
      </div>

      {/* SOURCE FOOTER */}
      <div className="cld-src-row">
        <div className="cld-src-tag">ambi_data_vaccine_uptake.json · Patel Lab CPHD dataset v3</div>
        <div className="cld-src-tag">Rennert L et al. (2024) · Public Health Practice · doi:10.1016/j.puhip.2024.100550</div>
        <div className="cld-src-tag">Gupta PS et al. (2022) · Preventive Medicine</div>
        <div className="cld-src-tag">Woodson et al. (2024) · J Public Health Mgmt Practice</div>
        <div className="cld-src-tag">CDPH Protect Chicago+ · chicago.gov</div>
      </div>
    </div>
  );
}
